apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: test-dep
spec: 
 replicas: 2
 strategy: 
  type: RollingUpdate 
 selector: 
  matchLabels: 
   app: test-app 
 template: 
   metadata: 
    labels: 
     app: test-app 
     env: prod 
   spec: 
    containers: 
    - name: test-container 
      image: souhaibhsoumi/frontendproject:1
