apiVersion: v1
kind: Service
metadata:
 name: test-service
spec:
 type: NodePort
 selector:
   app: test-app
   env: prod
 ports:
 - name: test
   protocol: TCP
   port: 3002
   targetPort: 3002
   nodePort: 32222
