apiVersion: v1
kind: Service
metadata:
 name: test-service
spec:
 type: NodePort
 selector:
   app: test-app
   env: prod
 ports:
 - name: test
   protocol: TCP
   port: 3001
   targetPort: 3001
   nodePort: 32220
